### ISSUE TITLE
Need Help with Exercise 2 Qs 4&5

### ISSUE THREAD

**Issue by marleyhaupt1** [pearselab/r-intro-marleyhaupt1#3]
Sorry! Me again.

On exercise 2 question 4, the code I've written seems to work except it does two things I don't understand (1) It tells me that 15 is prime, and it isn't (2) I can't get it to print the value of i and the words "Good: NUMBER" or "Job: Number" on the same line.

On exercise 2 question 5, am having some trouble with the gompertz curve equation. I thought that e was coded as exp in r but the way my code is currently written the function returns an error message "Error in exp^(-c*time): non-numeric argument to binary operator".  Is the problem with using exp or is there something else going on? I think that the problem may be more of a result of the way I am reading the equation than a result of me not being able to do a proper function.

Thanks again!

**Comment by marleyhaupt1** [comment]
I figured out Question 4

**Comment by willpearse** [comment]
Don't apologise! I'm your teacher: I'm meant to teach you!... It's a shame that my being seven hours ahead of the class is making things a bit slower than they might otherwise be.

In R, `exp` is a _function_, not a _vector_. Thus writing `exp^` isn't going to work, it should be `exp(a*exp(`. The error message you get is a bit obscure, but I think it's referring to `a*exp`: `*` is a binary operator (it is an operator, and it takes two things), and while `a` is a numeric, `exp^` is not, so it throws a hissy-fit there.

Sometimes error messages are confusing, and I will be going over some common gotchas with them in the next lecture. Remember that _everything in R is an object_: this also goes for error messages, so when something causes an error (like your use of `exp`) this is returned back to the `*` operator, and so it complains that it can't multiply a number by an error message. Weird, I realise, but there we go....

**Comment by marleyhaupt1** [comment]
Thanks! 
I took out the carots and now my function now looks like: 
gompertz<-function(time,a,b,c){
      y<-a_exp(-b_exp(-c*time))
      return(y)
}
(I realize you could have just looked at my code... oh well I guess). For some reason when I run the function now it always returns exactly the value that I put in for a. It just seems weird. What's the point of creating a function and naming it after yourself if the answer is always just the first parameter? I think I must be doing something wrong still.

**Comment by willpearse** [comment]
There's an error in your function: `aexp` won't work, it should be `a*exp(`...

Try that, then it'l work I think :D

**Comment by marleyhaupt1** [comment]
Cool beans. I just recommitted my code, but it still is being weird even with the astrix. :/ super pain sorry

**Comment by willpearse** [comment]
It works when I look at it, which (I guess) is why you closed the issue.
